apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "18"
  creationTimestamp: "2020-04-13T04:01:19Z"
  generation: 40
  labels:
    app: heartbeat
  name: heartbeat
  namespace: default
  resourceVersion: "1054946"
  selfLink: /apis/apps/v1/namespaces/default/deployments/heartbeat
  uid: 6e38b8fb-7d3b-11ea-a29d-42010a8a0018
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: heartbeat
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: heartbeat
    spec:
      containers:
      - env:
        - name: MY_cloud
          value: gcp
        - name: MY_node
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: MY_namespace
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: MY_serviceAccount
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.serviceAccountName
        - name: MY_app
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.labels['app']
        image: gcr.io/poseidon-xwang/heartbeat@sha256:09f862d6d749e44dc4bdaecbff7a3139c1d277cccfa87b0851f4b013a7fa0a3c
        imagePullPolicy: IfNotPresent
        name: heartbeat
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-04-13T19:46:01Z"
    lastUpdateTime: "2020-04-13T19:46:01Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2020-04-13T19:02:19Z"
    lastUpdateTime: "2020-04-13T19:54:40Z"
    message: ReplicaSet "heartbeat-7b8945fc75" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 40
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
